package com.wantime.wbangapp.request

object APIRequestPath {
    const val login_url = "login"
    const val authHome_url = "home"
    const val upload_url = "upload"
    const val news_url = "xiandu/category/wow"
    const val ariticle_list_url = "articleList/{page}/{size}"
    const val launch_url = "launchAd"
    const val popups_url = "popups"
    const val cancelOrder_url = "cancelOrder/{id}"
    const val confirmOrder_url = "confirmOrder"
    const val platform_url = "platform"
    const val autoAuth_url = "autoAuth"
    const val userInfo_url = "userInfo"
    const val platformApply_url = "platformApply"
    const val publicPlatformList_url = "publicPlatformList"
    const val PAQTaskList_url = "PAQTaskList/{page}/{size}"
    const val authRecord_url = "authRecord/{page}/{size}"
    const val represent_url = "represent"
    const val representRecord_url = "representRecord/{page}/{size}"
    const val exclusivePlatformList_url = "exclusivePlatformList"
    const val exclusiveAuth_url = "exclusiveAuth"
    const val cancelAuth_url = "cancelAuth/{orderId}"
    const val getOnlineNumber_url = "getOnlineNumber" //获取在线数量
    const val QRCodeAuth_url="QRCodeAuth"
    const val scanCode_url="scanCode"
    const val checkUpdate_url="checkUpdate"
    const val updateRecord_url="updateRecord"
    const val sendEmail_url="sendEmail"
    const val resetPassword_url="modifyPassword"
    const val setRemark_url="setRemark"
    const val idCardVerif_url="idCardVerify"
    const val userAgreementUrl="userAgreement"
    const val disclaimerUrl="disclaimer"
    const val registerUrl="register"
    const val protocolUrl="protocol"
    const val sendSmsUrl="sendSms"
    const val rechargeRecordUrl="rechargeRecord/{page}/{size}"
    const val myAgencyListUrl="myAgencyList/{page}/{size}"
    const val myUserListUrl="myUserList/{page}/{size}"
    const val addRemarkUrl="addRemark"
    const val bannedUserUrl="bannedUser/{id}"
    const val rechargeUrl="recharge"
    const val keyRechargeUrl="recharger/recharge"
    const val userUpgradeUrl="userUpgrade/{id}"
    const val updateNicknameUrl="updateNickname"
    const val afterSale="afterSale/{id}"
    const val userLogoutUrl="userLogout"
    const val bathchRegisterUrl="batchRegister"

}